### ISSUE TITLE
ERROR string indices must be integers

### ISSUE THREAD

**Issue by sdtptj** [eezd/EhFavDL#1]
在填写config.yaml的exh cookie前程序启动正常，填写cookie之后报错 【2024-04-14T01:11:00.248922+0800 ERROR string indices must be integers
】

**Comment by eezd** [comment]
请确保 `config.yaml` 中的冒号`:`后面跟着**空格**

```yaml
# 错误示范
cookies:
  ipb_member_id:123456
  ipb_pass_hash:asdjkasdk123
  igneous:dasad15a

# 正确
cookies:
  ipb_member_id: 123456
  ipb_pass_hash: asdjkasdk123
  igneous: dasad15a
```
